"""Verify all FG-DS seed-42 exports and firmware bundles before flashing."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

try:
    from .stream_vectors_fgds_strict import (
        FULL_TEST_ROWS,
        sha256_file,
        verify_bundle,
        verify_export,
    )
    from .verify_results_fgds_strict import read_reference, read_replay_source_rows
except ImportError:
    from stream_vectors_fgds_strict import (
        FULL_TEST_ROWS,
        sha256_file,
        verify_bundle,
        verify_export,
    )
    from verify_results_fgds_strict import read_reference, read_replay_source_rows


REPO_ROOT = Path(__file__).resolve().parents[3]
EXPORTER = (
    REPO_ROOT
    / "deployment"
    / "firmware_export"
    / "wsnds_rfkd_hil"
    / "export_fgds_seed42_deployment.py"
)
EXPORT_DIRS = {
    "student_A": REPO_ROOT
    / "deployment"
    / "firmware_export"
    / "wsnds_rfkd_hil"
    / "generated_fgds_student_A_seed42",
    "student_B": REPO_ROOT
    / "deployment"
    / "firmware_export"
    / "wsnds_rfkd_hil"
    / "generated_fgds_student_B_seed42",
}
BUNDLE_DIRS = {
    ("student_A", "esp32c3"): REPO_ROOT
    / "deployment"
    / "hardware_hil"
    / "build"
    / "fgds_student_A_seed42_esp32c3",
    ("student_A", "arduino_r4"): REPO_ROOT
    / "deployment"
    / "hardware_hil"
    / "build"
    / "fgds_student_A_seed42_arduino_r4",
    ("student_B", "esp32c3"): REPO_ROOT
    / "deployment"
    / "hardware_hil"
    / "build"
    / "fgds_student_B_seed42_esp32c3",
    ("student_B", "arduino_r4"): REPO_ROOT
    / "deployment"
    / "hardware_hil"
    / "build"
    / "fgds_student_B_seed42_arduino_r4",
}


def run_preflight() -> dict[str, Any]:
    exporter_sha256 = sha256_file(EXPORTER)
    exports: dict[str, dict[str, Any]] = {}
    export_rows: dict[str, dict[int, int]] = {}
    export_summaries: dict[str, dict[str, Any]] = {}

    for student, generated_dir in EXPORT_DIRS.items():
        manifest = verify_export(generated_dir)
        report = manifest["_verified_report"]
        provenance = report["provenance"]
        gates = report["gates"]
        if provenance.get("exporter_sha256") != exporter_sha256:
            raise RuntimeError(
                f"{student} was generated by a different FG-DS exporter implementation"
            )
        overlap = provenance.get("feature_overlap_audit", {})
        if any(
            overlap.get(key) != 0
            for key in [
                "train_validation_feature_overlap",
                "train_test_feature_overlap",
                "validation_test_feature_overlap",
            ]
        ):
            raise RuntimeError(f"{student} export is not feature-group disjoint")
        if gates.get("full_test_rows") != FULL_TEST_ROWS:
            raise RuntimeError(f"{student} export does not contain the full FG-DS test set")

        replay_rows = read_replay_source_rows(generated_dir / "hil_replay_vectors.csv")
        references = read_reference(generated_dir / "hil_reference_predictions.csv")
        expected_ids = set(range(FULL_TEST_ROWS))
        if set(replay_rows) != expected_ids or set(references) != expected_ids:
            raise RuntimeError(f"{student} replay/reference row IDs are incomplete")
        if len(set(replay_rows.values())) != FULL_TEST_ROWS or min(replay_rows.values()) < 0:
            raise RuntimeError(f"{student} replay source rows are not unique and non-negative")
        if any(
            replay_rows[row_id] != references[row_id]["source_row_index"]
            for row_id in range(FULL_TEST_ROWS)
        ):
            raise RuntimeError(f"{student} replay/reference source rows differ")

        exports[student] = manifest
        export_rows[student] = replay_rows
        export_summaries[student] = {
            "generated_dir": str(generated_dir),
            "export_id": manifest["export_id"],
            "test_rows": gates["full_test_rows"],
            "fixed_vs_fp32_agreement": gates["fixed_vs_fp32_agreement"],
            "fp32_macro_f1": gates["fp32_macro_f1"],
            "fixed_macro_f1": gates["fixed_macro_f1"],
            "macro_f1_drop": gates["macro_f1_drop"],
            "passes_original_0_01_code_level_gate": gates[
                "passes_original_0_01_code_level_gate"
            ],
            "passes_frozen_0_03_reporting_tolerance": gates[
                "passes_frozen_0_03_reporting_tolerance"
            ],
            "split_hashes": provenance["split_hashes"],
            "scaler_sha256": provenance["scaler_sha256"],
            "replay_vectors_sha256": sha256_file(
                generated_dir / "hil_replay_vectors.csv"
            ),
            "reference_predictions_sha256": sha256_file(
                generated_dir / "hil_reference_predictions.csv"
            ),
        }

    if export_rows["student_A"] != export_rows["student_B"]:
        raise RuntimeError("Student A and Student B do not use the same FG-DS test rows")
    if exports["student_A"]["export_id"] == exports["student_B"]["export_id"]:
        raise RuntimeError("Student A and Student B exports have the same identity")
    for field in ["split_hashes", "scaler_sha256", "replay_vectors_sha256"]:
        if export_summaries["student_A"][field] != export_summaries["student_B"][field]:
            raise RuntimeError(f"Student exports disagree on common data contract: {field}")

    bundle_ids: set[str] = set()
    bundle_summaries: dict[str, dict[str, Any]] = {}
    for (student, board), bundle_dir in BUNDLE_DIRS.items():
        manifest = verify_bundle(bundle_dir, exports[student])
        if manifest.get("board") != board or manifest.get("student") != student:
            raise RuntimeError(
                f"Bundle directory is paired with the wrong board/student: {bundle_dir}"
            )
        if manifest["bundle_id"] in bundle_ids:
            raise RuntimeError("Two board/model pairs have the same firmware bundle ID")
        bundle_ids.add(manifest["bundle_id"])
        label = f"{board}_{student}"
        bundle_summaries[label] = {
            "bundle_dir": str(bundle_dir),
            "board": board,
            "student": student,
            "bundle_id": manifest["bundle_id"],
            "export_id": manifest["export_id"],
            "sketch_file": manifest["sketch_file"],
            "sketch_sha256": manifest["transformed_sketch_sha256"],
        }

    return {
        "status": "ready_for_compile_flash_and_hil",
        "scope": (
            "Host-side preflight only. This does not claim that firmware compiled, "
            "was flashed, or executed on either physical board."
        ),
        "protocol_id": "wsnds_feature_group_split_train_only_scaler_5seed_v1",
        "full_test_rows_per_board_model_pair": FULL_TEST_ROWS,
        "planned_full_test_board_predictions": 4 * FULL_TEST_ROWS,
        "exporter_sha256": exporter_sha256,
        "exports": export_summaries,
        "bundles": bundle_summaries,
    }


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output-json", type=Path)
    args = parser.parse_args()
    result = run_preflight()
    encoded = json.dumps(result, indent=2) + "\n"
    if args.output_json is not None:
        output = args.output_json.resolve()
        for protected_root in [*EXPORT_DIRS.values(), *BUNDLE_DIRS.values()]:
            try:
                output.relative_to(protected_root.resolve())
            except ValueError:
                continue
            raise RuntimeError(
                f"Preflight output cannot be written inside a verified input: {output}"
            )
        if output.exists():
            raise FileExistsError(f"Refusing to overwrite preflight output: {output}")
        output.parent.mkdir(parents=True, exist_ok=True)
        temporary = output.with_suffix(output.suffix + ".tmp")
        if temporary.exists():
            raise FileExistsError(f"Stale preflight temporary exists: {temporary}")
        temporary.write_text(encoded, encoding="utf-8")
        temporary.replace(output)
        print(output)
    else:
        print(encoded, end="")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
